site_name: Marvel Laundry Shop
nav:
  - Home: index.md
  - Contact Details: about_us.md
  - Prices: prices.md
  - Services: services.md

theme:
  name: material
  palette: 
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode



extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
    - icon: fontawesome/brands/facebook
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter

plugins:
  - mkdocs-video:
      mark: "custom-marker"
  

copyright: Copyright &copy; Alvin Carpio  
